### ISSUE TITLE
undefined reference to `pow' when running the compiler

### ISSUE THREAD

**Issue by sztomi** [ja3067/Coral#12] opened 2019-02-16 00:10 UTC
Using a freshly built `coral` executable from master, I get the following errors:

```
➜ ./_build/src/coral.native demos/gcd-demo.cl
/tmp/gcd-demo-101d97.o: In function `int_exp':
Coral:(.text+0x24b): undefined reference to `pow'
/tmp/gcd-demo-101d97.o: In function `float_exp':
Coral:(.text+0xb17): undefined reference to `pow'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Am I holding it wrong? Is there another dependency I need to install?

**Comment by ja3067** [comment] 2019-02-16 01:23
That's odd. pow is just the c function. I can't reproduce, but it's conceivable that you need to link the cmath library when you compile. Can you try changing the two invocations of clang in coral.ml to include the math.h library? You can probably add ```-lm``` or ```-lmath``` to the two lines. I think that might solve it.

**Comment by sztomi** [comment] 2019-02-16 11:27
Yeah, adding `-lm` does work. I'm curious why it's not needed in other cases.

**Comment by ja3067** [comment] 2019-02-16 16:51
Just pushed an update that adds this. The pow function links in the C pow function included in math.h. On MacOS at least, where we've done most of our development, you don't really need to link it in, but I think that's different on Linux. Closing since I think this is resolved.

**Closed by ja3067** 2019-02-16 16:51 UTC
